apps/blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, CategoryPostListView, TagPostListView

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('<slug:slug>/', PostDetailView.as_view(), name='post_detail'),
    path('category/<slug:category_slug>/', CategoryPostListView.as_view(), name='post_list_by_category'),
    path('tag/<slug:tag_slug>/', TagPostListView.as_view(), name='post_list_by_tag'),
]

apps/charity/urls.py
from django.urls import path

from apps.charity.views import HomePageView, AboutPageView, DetailPageView

app_name = 'charity'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about-us/', AboutPageView.as_view(), name='about_us'),
]

apps/contacts/urls.py
from django.urls import path
from .views import ContactCreateView, contact_success_view

app_name = 'contact'

urlpatterns = [
    path('', ContactCreateView.as_view(), name='contact_create'),
    path('success/', contact_success_view, name='contact_success'),
]

apps/events/urls.py
# apps/events/urls.py
from django.urls import path
from .views import EventListView, EventDetailView

app_name = 'events'

urlpatterns = [
    path('', EventListView.as_view(), name='event_list'),
    path('<slug:slug>/', EventDetailView.as_view(), name='event_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.charity.urls', namespace='pages')),
    path('services/', include('apps.services.urls', namespace='services')),
    path('campaigns/', include('apps.campaigns.urls', namespace='campaigns')),
    path('events/', include('apps.events.urls', namespace='events')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('contact/', include('apps.contacts.urls', namespace='contact')),
    path('donations/', include('apps.donations.urls', namespace='donations')),
    path('editorjs/', include('django_editorjs_fields.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/layouts/banner.html
<div class="slider-area" style="background-image: url({{ home_banner_url }})">
    <div class="slider-active">
        {% for item in home_slides %}
            <div class="single-slider slider-height d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-6 col-lg-6 col-md-8 col-sm-10">
                            <div class="hero__caption">
                                <h1 data-animation="fadeInUp" data-delay=".6s">{{ item.title }}</h1>
                                <P data-animation="fadeInUp" data-delay=".8s">{{ item.description }}</P>
                                <!-- Hero-btn -->
                                <div class="hero__btn">
                                    {% if item.action_btn_text %}
                                        <a href="{{ action_btn_link }}" class="btn hero-btn mb-10"
                                           data-animation="fadeInLeft" data-delay=".8s">{{ item.action_btn_text }}</a>
                                    {% endif %}
                                    {% if item.email_btn_text %}
                                        <a href="mailto:{{ item.email_btn_link }}" class="cal-btn ml-15"
                                           data-animation="fadeInRight" data-delay="1.0s">
                                            <i class="flaticon-null"></i>
                                            <p>{{ item.email_btn_text }}</p>
                                        </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

templates/layouts/footer.html
{% load static %}
<footer>
    <div class="footer-wrapper section-bg2" data-background="{{ footer_bg_url }}">
        <!-- Footer Top-->
        <div class="footer-area footer-padding">
            <div class="container">
                <div class="row d-flex justify-content-between">
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="single-footer-caption mb-30">
                                <div class="footer-tittle">
                                    <div class="footer-logo mb-20">
                                        <a href="{% url 'charity:home' %}"><img src="{{ site_logo_reverse_url }}" alt="{{ site_logo_reverse_caption }}"></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-5">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Contact Info</h4>
                                <ul>
                                    <li>
                                        <p>Address :{{ contact_address }}</p>
                                    </li>
                                    <li><a href="tel:{{ contact_phone }}">Phone : {{ contact_phone }}</a></li>
                                    <li>
                                        <a href="mailto:{{ contact_email }}">Email : {{ contact_email }}</a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-5">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Important Link</h4>
                                <ul>
                                    <li><a href="{% url 'charity:about_us' %}">About Us</a></li>
                                    <li><a href="{% url 'campaigns:campaign_list' %}">Campaigns</a></li>
                                    <li><a href="{% url 'contact:contact_create' %}">Contact Us</a></li>
                                    <li><a href="{% url 'donations:donation_create' %}">Support</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-5">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>{{ newsletter_title }}</h4>
                                <div class="footer-pera footer-pera2">
                                    <p>{{ newsletter_subtitle }}</p>
                                </div>
                                <!-- Form -->
                                <div class="footer-form">
                                    <div id="mc_embed_signup">
                                        <form target="_blank" action="" method="get" class="subscribe_form relative mail_part">
                                            <input type="email" name="email" id="newsletter-form-email" placeholder="{{ newsletter_email_placeholder }}" class="placeholder hide-on-focus" onfocus="this.placeholder = ''"  onblur="this.placeholder = '{{ newsletter_email_placeholder }}'">
                                            <div class="form-icon">
                                                <button type="submit" name="submit" id="newsletter-submit" class="email_icon newsletter-submit button-contactForm">
                                                    <img src="{{ send_icon_url }}" alt="{{ send_icon_caption }}">
                                                </button>
                                            </div>
                                            <div class="mt-10 info"></div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- footer-bottom -->
        <div class="footer-bottom-area">
            <div class="container">
                <div class="footer-border">
                    <div class="row d-flex justify-content-between align-items-center">
                        <div class="col-xl-10 col-lg-9 ">
                            <div class="footer-copy-right">
                                <p>
                                    Copyright &copy; <script>document.write(new Date().getFullYear());</script>
                                    All rights reserved | Developed by <a href="" target="_blank">Mamunur Rashid</a>
                                </p>
                            </div>
                        </div>
                        <div class="col-xl-2 col-lg-3">
                            <div class="footer-social f-right">
                                {% for item in socials %}
                                	<a href="{{ item.link }}"><i class="{{ item.social.fontawesome_class }}" title="{{ item.social.title }}"></i></a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

<!-- Scroll Up -->
<div id="back-top">
    <a title="Go to Top" href="index.html#"> <i class="fas fa-level-up-alt"></i></a>
</div>

templates/layouts/header.html
{% load static %}
{% include 'includes/preloader.html' %}
<header>
    <div class="header-area">
        <div class="main-header ">
            {% include 'layouts/top-bar.html' %}
            {% include 'layouts/navbar.html' %}
        </div>
    </div>
</header>

templates/layouts/navbar.html
{% load static %}
<div class="header-bottom  header-sticky">
    <div class="container-fluid">
        <div class="row align-items-center">
            <!-- Logo -->
            <div class="col-xl-2 col-lg-2">
                <div class="logo">
                    <a href="{% url 'pages:home' %}"><img src="{% static 'img/logo/logo.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-xl-10 col-lg-10">
                <div class="menu-wrapper  d-flex align-items-center justify-content-end">
                    <!-- Main-menu -->
                    <div class="main-menu d-none d-lg-block">
                        <nav>
                            <ul id="navigation">
                                <li><a href="{% url 'pages:home' %}">Home</a></li>
                                <li><a href="{% url 'pages:about_us' %}">About</a></li>
                                <li><a href="{% url 'campaigns:campaign_list' %}">latest causes</a></li>
                                <li><a href="{% url 'events:event_list' %}">social events </a></li>
                                <li><a href="{% url 'blog:post_list' %}">Blog</a></li>
                                <li><a href="{% url 'contact:contact_create' %}">Contact</a></li>
                            </ul>
                        </nav>
                    </div>
                    <!-- Header-btn -->
                    <div class="header-right-btn d-none d-lg-block ml-20">
                        <a href="{% url 'donations:donation_create' %}" class="btn header-btn">Donate</a>
                    </div>
                </div>
            </div>
            <!-- Mobile Menu -->
            <div class="col-12">
                <div class="mobile_menu d-block d-lg-none"></div>
            </div>
        </div>
    </div>
</div>

templates/layouts/page-header.html
<div class="slider-area2">
    <div class="slider-height2 d-flex align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap hero-cap2 pt-70 text-center">
                        <h2>{{ banner_title }}</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/layouts/sidebar.html
<div class="blog_right_sidebar">
    <aside class="single_sidebar_widget search_widget">
        <form action="blog.html#">
            <div class="form-group">
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder='Search Keyword' onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Keyword'">
                    <div class="input-group-append">
                        <button class="btns" type="button"><i class="ti-search"></i></button>
                    </div>
                </div>
            </div>
            <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                    type="submit">Search
            </button>
        </form>
    </aside>
    <aside class="single_sidebar_widget post_category_widget">
        <h4 class="widget_title" style="color: #2d2d2d;">Categories</h4>
        <ul class="list cat-list">
            {% for category in categories %}
            	<li>
                    <a href="{{ category.get_absolute_url }}" class="d-flex">
                        <p>{{ category.title }}</p>
                        <p>({{ category.posts_count }})</p>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </aside>
    <aside class="single_sidebar_widget popular_post_widget">
        <h3 class="widget_title" style="color: #2d2d2d;">Recent Post</h3>
        {% for recent_post in recent_posts %}
        	<div class="media post_item">
                <img src="{{ recent_post.image.icon.url }}" alt="{{ recent_post.title }}">
                <div class="media-body">
                    <a href="{{ recent_post.get_absolute_url }}">
                        <h3 style="color: #2d2d2d;">{{ recent_post.title }}</h3>
                    </a>
                    <p>{{ recent_post.get_date }}</p>
                </div>
            </div>
        {% endfor %}
    </aside>
    <aside class="single_sidebar_widget tag_cloud_widget">
        <h4 class="widget_title" style="color: #2d2d2d;">Tags</h4>
        <ul class="list">
            {% for tag in tags %}
            	<li>
                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </aside>
    <aside class="single_sidebar_widget newsletter_widget">
        <h4 class="widget_title" style="color: #2d2d2d;">Newsletter</h4>
        <form action="blog.html#">
            <div class="form-group">
                <input type="email" class="form-control" onfocus="this.placeholder = ''"
                       onblur="this.placeholder = 'Enter email'" placeholder='Enter email' required>
            </div>
            <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                    type="submit">Subscribe
            </button>
        </form>
    </aside>
</div>

templates/layouts/top-bar.html
<div class="header-top d-none d-lg-block">
    <div class="container-fluid">
        <div class="col-xl-12">
            <div class="row d-flex justify-content-between align-items-center">
                <div class="header-info-left d-flex">
                    <ul>
                        <li>Phone: <a class="text-dark" href="tel:{{ contacts_phone }}">{{ contacts_phone }}</a></li>
                        <li>Email: <a class="text-dark" href="mailto:{{ contacts_email }}">{{ contacts_email }}</a></li>
                    </ul>
                    <div class="header-social">
                        <ul>
                            {% for item in socials %}
                            	<li><a href="{{ item.link }}"><i class="{{ item.social.fontawesome_class }}" title="{{ item.social.title }}"></i></a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="header-info-right d-flex align-items-center">
                    <div class="select-this">
                        <form>
                            <div class="select-itms">
                                <select name="select" id="select1" disabled>
                                    <option selected value="eng">English</option>
                                    <option value="bn">Bengali</option>
                                    <option value="ar">Arabic</option>
                                    <option value="hn">Hindi</option>
                                </select>
                            </div>
                        </form>
                    </div>
                    <ul class="contact-now">
                        <li><a href="index.html#">Subscribe Now</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>